workspace:
  base: /go
  path: src/github.com/cj123/canijailbreak.com

pipeline:
  build:
    image: golang:1.11
    commands:
    - export GO111MODULE=on
    - go build -o jailbreak-generate .
    - ./jailbreak-generate -i ./jailbreaks.yml -o ./static
    - cd static
    - tar czf ../canijailbreak.com.tar.gz *

  deploy:
    secrets: [ plugin_key, DEPLOY_HOSTS, DEPLOY_TARGET, DEPLOY_USER ]
    image: drillster/drone-rsync
    source: ./canijailbreak.com.tar.gz
    user: $DEPLOY_USER
    delete: false
    recursive: true
    hosts: [ $DEPLOY_HOSTS ]
    target: /var/www/canijailbreak.com
    script:
    - cd /var/www/canijailbreak.com
    - bash do-release.sh
    when:
      branch: master

  cloudflare:
    image: seejy/drone-cloudflare
    secrets: [ CLOUDFLARE_EMAIL, CLOUDFLARE_APIKEY ]
    domain: canijailbreak.com
    when:
      branch: master