language: go

go:
  - 1.12

install:
  - export GO111MODULE=on
  - go get ./...
  - go test -cover ./...
  - go build -o canijailbreak .

script:
  ./canijailbreak -i jailbreaks.yml -o static/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: static
  keep_history: true
  fqdn: canijailbreak.com
  on:
    branch: master
