language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - PATH=$PATH:.node_modules/bin

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - npm install

script:
  - gulp build
  - php app/console doctrine:schema:update --force
  - php app/console jailbreaks:migrate
  - phpunit -c app/
